name: build & test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    environment: ci
    services:
      neo4j:
        image: neo4j:community
        env:
          NEO4J_AUTH: none
        options: >-
          --health-cmd "neo4j status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 7474:7474
        - 7687:7687
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create private key file used for JWT signing
      run: |
        cd src/test/resources &&
          openssl genpkey -outform der -algorithm rsa -out pkey.der &&
          openssl pkcs8 -topk8 -inform der -outform der -in pkey.der -out pkey.pk8 -nocrypt
    - name: Move CI conf file into place
      run: mv src/test/resources/application.ci.conf src/test/resources/application.conf
    - name: Run tests
      run: sbt clean coverage test
    - name: Upload coverage data to Coveralls
      run: |
        echo "Token is «$COVERALLS_REPO_TOKEN»" | tee > /tmp/token.txt &&
          cat "/tmp/token.txt" &&
          sbt 'eval sys.env.getOrElse("COVERALLS_REPO_TOKEN", "").length' coverageReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
