name: build & test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    environment: ci
    services:
      neo4j:
        image: neo4j:community
        env:
          NEO4J_AUTH: none
        options: >-
          --health-cmd "neo4j status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 7474:7474
        - 7687:7687
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Cache Scala
      uses: coursier/cache-action@v6
    - name: Set up Scala, SBT and JDK
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:21
        apps: sbt sbtn
    - name: Create private key file used for JWT signing
      run: |
        cd src/test/resources &&
          openssl genpkey -outform der -algorithm rsa -out pkey.der &&
          openssl pkcs8 -topk8 -inform der -outform der -in pkey.der -out pkey.pk8 -nocrypt
    - name: Move CI conf file into place
      run: mv src/test/resources/application.ci.conf src/test/resources/application.conf
    - name: Run tests
      run: sbtn 'clean; coverage; test; coverageReport'
    - name: Output SHA of CODECOV_TOKEN
      run: |
        echo -n "$CODECOV_TOKEN" | sha256sum | awk '{printf "SHA256 of CODECOV_TOKEN is %s\n", $1}'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
