name: build & test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    environment: ci
    services:
      neo4j:
        image: neo4j:community
        env:
          NEO4J_AUTH: none
        options: >-
          --health-cmd "neo4j status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 7474:7474
        - 7687:7687
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create private key file used for JWT signing
      run: |
        cd src/test/resources &&
          openssl genpkey -outform der -algorithm rsa -out pkey.der &&
          openssl pkcs8 -topk8 -inform der -outform der -in pkey.der -out pkey.pk8 -nocrypt
    - name: Move CI conf file into place
      run: mv src/test/resources/application.ci.conf src/test/resources/application.conf
    - name: Fetch CodeClimate test reporter and run its before-build
      run: |
        echo -n "$CC_TEST_REPORTER_ID" | sha256sum | awk '{printf "Token SHA256 is %s\n", $1}'
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run tests
      run: sbt clean coverage test
    - name: Upload coverage data to CodeClimate
      run: |
        echo -n "$CC_TEST_REPORTER_ID" | sha256sum | awk '{printf "Token SHA256 is %s\n", $1}'
        ./cc-test-reporter after-build
