name: sbt test

on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk-jammy
    services:
      neo4j:
        image: neo4j:community
        env:
          NEO4J_AUTH: none
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
    - name: Create private key file used for JWT signing
      run: |
        cd src/test/resources &&
          openssl genpkey -outform der -algorithm rsa -out pkey.der &&
          openssl pkcs8 -topk8 -inform der -outform der -in pkey.der -out pkey.pk8 -nocrypt
    - name: Move CI conf file into place
      run: mv src/test/resources/application.ci.conf src/test/resources/application.conf
    - name: Run tests
      run: sbt test
